#define PROGRAM_NAME        "OptiPNG"
#define PROGRAM_DESCRIPTION "Advanced PNG optimizer"
#define PROGRAM_VERSION     "0.6.5"
#define PROGRAM_COPYRIGHT   "Copyright (C) 2001-2011 Cosmin Truta"
#define PROGRAM_URI         "http://optipng.sourceforge.net/"
